# Use a specific SQL Server 2022 image (ensure it's from a trusted source)
FROM omjee/sqlserver2022

# Accept the End User License Agreement and set a strong SA password
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=DevSecOps1

# Expose the SQL Server port to the host
EXPOSE 1433
